Repository ohmybash/oh-my-bash, pull requests merged in 2020-02, with the labels that each got.

#104 plugins/battery: Attempt to fix #68
  plugins/battery/battery.plugin.sh
Labels: P2 - Important, bug-fix

#103 lib/utils: Code quality improvement
  lib/utils.sh
Labels: P2 - Important, improvement

#91 plugins/git: Add git cherry-pick -s
  plugins/git/git.plugin.sh
Labels: P3 - Normal

#87 LICENSE: Change on GPLv2 from WTFPL
  LICENSE.md
  LICENSE.txt
Labels: P3 - Normal
