Repository ohmybash/oh-my-bash, pull requests merged in 2020-06, with the labels that each got.

#133 Extra theme 'garo'
  themes/garo/garo.theme.sh
Labels: P3 - Normal, community-feature

#118 plugins/ansible: Ansible plugin added
  plugins/ansible/README.md
  plugins/ansible/ansible.plugin.sh
Labels: P3 - Normal, community-feature

#130 completions/minikube: Add minikube completion
  completions/minikube.completion.sh
Labels: P3 - Normal, community-feature

#153 aliases/general: Add fix_term alias to reset the terminal
  aliases/general.aliases.sh
Labels: P3 - Normal, community-feature

#37 themes/powerline: Fix powerline theme implicitly depends on bash's IFS
  themes/powerline/powerline.base.sh
Labels: P2 - Important, bug-fix

#95 README: Update links for screenshots
  README.md
Labels: P3 - Normal
