Repository ohmybash/oh-my-bash, pull requests merged in 2023-04, with the labels that each got.

#181 base.theme.sh: use “command” to run git and svn everywhere
  completions/svn.completion.sh
  lib/git.sh
  lib/omb-prompt-base.sh
  plugins/git/git.plugin.sh
  themes/agnoster/agnoster.theme.sh
  themes/cooperkid/cooperkid.theme.sh
  themes/cupcake/cupcake.theme.sh
  themes/doubletime/doubletime.theme.sh
  themes/hawaii50/hawaii50.theme.sh
  themes/mbriggs/mbriggs.theme.sh
  themes/rana/rana.theme.sh
  themes/sexy/sexy.theme.sh
Labels: bug-fix, P2 - Important

#158 lib, themes: Preserve users' PROMPT_DIRTRIM
  lib/shopt.sh
  themes/agnoster/agnoster.theme.sh
  themes/roderik/roderik.theme.sh
  themes/vscode/vscode.theme.sh
Labels: in progress :construction:, community-feature, P3 - Normal

#132 lib/theme-and-appearance: Fix broken ls-colors
  aliases/general.aliases.sh
  lib/bourne-shell.sh
  lib/utils.sh
Labels: in progress :construction:, bug-fix, P3 - Normal

#105 lib/directories: Add `cd` function, a clone of Zsh cd builtin command
  lib/directories.sh
Labels: in progress :construction:, improvement

#433 style: Remove trailing whitespace and missing final newlines
  .editorconfig
  .git-blame-ignore-revs
  .github/workflows/format.yml
  completions/gem.completion.sh
  completions/git_flow.completion.sh
  completions/jboss7.completion.sh
  completions/maven.completion.sh
  completions/virtualbox.completion.sh
  lib/base.sh
  plugins/bashmarks/README.md
  plugins/brew/README.md
  plugins/brew/brew.plugin.sh
  plugins/golang/golang.plugin.sh
  plugins/kubectl/README.md
  plugins/npm/README.md
  plugins/npm/npm.plugin.sh
  plugins/nvm/nvm.plugin.sh
  plugins/progress/progress.plugin.sh
  plugins/pyenv/pyenv.plugin.sh
  templates/bashrc.osh-template
  themes/absimple/absimple.theme.sh
  themes/hawaii50/hawaii50.theme.sh
  themes/n0qorg/n0qorg.theme.sh
  themes/pure/pure.theme.sh
  themes/pzq/pzq.theme.sh
  themes/sirup/sirup.theme.sh
  themes/zork/zork.theme.sh
  tools/install.sh
  tools/uninstall.sh
Labels: in progress :construction:
